# Rise-Chain Spammer Configuration
# Uses wallet-json/ folder at root automatically

rpc_url = "https://testnet.riselabs.xyz"
chain_id = 11155931
tps = 100
worker_amount = 5
min_delay_ms = 100
max_delay_ms = 200
create2_factory = "0x8628208543e2b16be283e30abec6fec7b91e5721"
